
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

demo-ui:
  replicaCount: 1

  image:
    repository: demo-rancher-registry:62701/demo-ui
    pullPolicy: Always
    tag: "1.0.0"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    hosts:
      - host: demo.k3d.localhost
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: demo.k3d.localhost
            servicePort: 80

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  useLinkerd: enabled

demo-api-first:
  replicaCount: 4

  image:
    repository: demo-rancher-registry:62701/demo-api-first
    pullPolicy: Always
    tag: "1.0.0"
 
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    hosts:
      - host: demo.k3d.api.localhost
        paths:
        - path: /
          pathType: Prefix
 
  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  useLinkerd: enabled

demo-api-second:
  replicaCount: 1

  image:
    repository: demo-rancher-registry:62701/demo-api-second
    pullPolicy: Always
    tag: "1.0.0"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  useLinkerd: enabled